
	<h2>EAD Finding Aids</h2>
	<p>The <a href="http://westernwaters.org/">Western Waters Digital Library</a> provides access to a variety of EAD finding aids, which you can use to identify special collections of interest when you are researching water issues requiring access to primary source materials. Selected materials in these finding aids may be available online, and you can use the information contained in the finding aids to plan your visit to the particular Special Collections department holding your items of interest. </p>

		<h3>Searching the Western Waters Digital Library for Finding Aids</h3>
		<p>The <a href="/misearch">Western Waters Advanced search page</a> contains an option to limit your search to EAD finding aids. Select EAD in the type box, and type the terms you wish to search for. </p>

		<p><img src="/img/ead.png" alt="EAD advanced search" /></p>

		<p>The benefit of searching the Western Waters Digital Library for primary source materials is the ability to search many relevent finding aids from multiple instutions at once, for example:</p>


		<h3>Brigham Young University</h3>
		<h4><a href="http://findingaid.lib.byu.edu/viewItem/MSS%20146">Arthur V. Watkins Papers</a></h4>
		<p> Arthur V. Watkins was elected to the United States Senate in November 1946 and represented the state of Utah until 1959. Between 1954 and 1957, Watkins sponsored legislation supporting the Upper Colorado River Storage Project. The project included the construction of many reservoirs for water storage and conservation. These smaller projects helped bring more water to Utah, benefiting agriculture by providing a reliable source of irrigation water and protecting them against potential droughts. The Arthur V. Watkins Papers include notes, correspondence and reports that shed light on his work in shaping water policy as a United States Senator.</p>

		<h4><a target="_blank" href="http://findingaid.lib.byu.edu/viewItem/MSS%2020">Wallace Foster Bennett Papers</a></h4>
		<p>Correspondence, speeches, bills, legislative resolutions, press   releases, financial records, statistical tables, photographs, printed   material, newspaper clippings, and notes document Wallace F. Bennett's   activities, political matters, and office administrations during his   time as a senator between 1948 and 1974 in Utah and Washington D.C. The   Wallace F. Bennett papers were created and compiled by Senator Wallace   F. Bennett and his staff during four six-year terms in the United States   Senate from 1950 to 1974. The papers reveal the immense changes that   occurred in the concerns of the United States Congress during the   twenty-four years of Bennett's service.</p>
		<p>&nbsp;</p>

		<h3>Colorado State University</h3>
		<h4><a href="http://lib.colostate.edu/archives/findingaids/water/wcwc.html" target="_blank">Colorado Water Congress Newsletters</a></h4>
		<p>The Colorado Water Congress was established in 1958 and since then has proved to be a forward-thinking organization in terms of lobbying and educating in relation to current water issues in the state.&nbsp; Their newsletter, published as Colorado Water Congress Newsletter (1958-1982) and Colorado Water Rights (1982-2007), has been the main mode of conveying various perspectives on significant water policy issues and covers the Colorado River and other basins.&nbsp; The publication, taken as a whole, shows trends, successes and failure for Colorado’s water resources for a crucial period in the state’s history.&nbsp; </p>

		<h4><a target="_blank" href="http://digitool.library.colostate.edu:80/R/?func=dbin-jump-full&amp;object_id=79246">Delph E. Carpenter and Family </a></h4>
		<p class="contentnew" >The &quot;Father of Interstate River   Compacts,&quot; Delph E. Carpenter (1877-1951) served the state of Colorado   as a lawyer, state senator and river commissioner. He wrote, negotiated   and promoted the Colorado River Compact, among others, following his   service as lead counsel in the Wyoming vs. Colorado suit. The collection   documents these and other professional activities (including cattle   breeding), as well as Carpenter's personal life and family. Materials   from his son Weld County Judge Donald A. Carpenter, pioneer father Leroy   S. Carpenter, and father-in-law and Civil War veteran Captain M. J.   Hogarty are prominent in the collection, as are documents concerning the   Union Colony of Colorado. Predominant material types include   correspondence, minutes, legal briefs, financial papers, reports,   publications, speeches, diaries, clippings, photographs, maps,   certificates, scrapbooks and artifacts.</p>

		<h4><a target="_blank" href="http://digitool.library.colostate.edu:80/R/?func=dbin-jump-full&amp;object_id=79250">Robert E. Glover </a></h4>
		<p>Robert E. Glover (1896-1984), a civil engineer from Ord, Nebraska, began   his life-long career as an engineer in the Denver office of the U. S.   Bureau of Reclamation in 1924.  Contained within the collection are   reports, correspondence, diaries, publications, and calculations   documenting work on the Boulder (Hoover) Dam, the Owyhee Dam, and the   Glen Canyon Dam.  He conducted significant research on concrete cooling,   dam construction, groundwater flow, cracks in dams, and more. A smaller   portion of the collection reflects Glover's personal life in terms of   family activities and hobbies, including birding, photography, and   environmentalism.</p>

		<h4><a target="_blank" href="http://digitool.library.colostate.edu:80/R/?func=dbin-jump-full&amp;object_id=79247">Ival V. Goslin Water Resources Collection </a></h4>
		<p>For over 50 years, Ival V. Goslin (1911-1991) worked in water resources.   The bulk of the collection contains records from the Colorado Water   Resources and Power Development Authority where Goslin served as the   first Executive Director and later as a consultant. The Authority (est.   1981) has conducted water project feasibility studies and created and   implemented financing programs for water and wastewater infrastructures.   The collection includes considerable basic engineering, environmental,   hydrologic, and economic data surrounding water planning in the 1980s.   Records from Goslin's career at the Upper Colorado River Commission and   Western Engineers, Inc. are also included. While serving as the director   of the Upper Colorado River Basin, Goslin was instrumental in obtaining   Congressional funding and approval for many large Western Reclamation   projects.  Common subjects are the filling of Lake Powell and the   effects on Rainbow Bridge National Monument, and the recreational use of   Jerry Creek Reservoirs. Materials include correspondence, newsletters,   reports, legislative drafts, news clippings, speeches, books, pamphlets,   slides, photographs, videos, and artifacts.</p>

		<h4><a target="_blank" href="http://digitool.library.colostate.edu:80/R/?func=dbin-jump-full&amp;object_id=79248">James L. Ogilvie </a></h4>
		<p>James L. Ogilvie (1911-1995), a civil engineer from Weld County,   Colorado, had a long and fruitful career with the U. S. Bureau of   Reclamation in the field of irrigation and water management.  Ogilvie   worked his way up through the Bureau on many projects throughout   Colorado, culminating in his appointment as Project Manager for the   Fryingpan-Arkansas project in southeast Colorado.  The collection   contains professional files related to Ogilvie’s career as well as desk   diaries, which provide insight into the Bureau’s work at the time.</p>

		<h4><a target="_blank" href="http://digitool.library.colostate.edu:80/R/?func=dbin-jump-full&amp;object_id=79249">National Water Resources Association </a></h4>
		<p>Formerly the National Reclamation Association, the National Water   Resources Association is a federation of water users in seventeen   western states whose mission is to advocate federal policies and   legislation for water resources on behalf of its members.  The   collection highlights the changing views and tactics of reclamation   leaders over crucial years in the history of reclamation, starting in   the 1930s and going through the 1970s.  It includes speeches, reports,   photographs, correspondence and memoranda. </p>
<p></p>        
	 
 <h3>Northwest Digital Archives</h3>

	  <h4><a href="/browse/index/32">Browse WWDL-related Finding aids</a></h4>
		<p>Finding aids on topics such as water rights, fisheries, and much more. NWDA provides access to Finding Aids from states such as Idaho, Montana, Oregon, Alaska, and Washington.</p>
		<p>&nbsp;</p>


  <h3>University of Utah</h3>

		<h4><a href="http://content.lib.utah.edu/cdm4/item_viewer.php?CISOROOT=/ww-EAD&amp;CISOPTR=13" target="_blank">John S. Boyden Papers</a></h4>
		<p>The John S. Boyden papers (1929-1980) contain correspondence,   biographical information, and documents relating to his dealings with   Native American issues, Utah water issues, and politics. He was an   attorney in Salt Lake City, Utah.</p>

		<h4><a href="http://content.lib.utah.edu/cdm4/item_viewer.php?CISOROOT=/ww-EAD&amp;CISOPTR=14" target="_blank">Stephen G. Boyden Papers</a></h4>
		<p>The Stephen G. Boyden papers (1945-1988) contain correspondence,   legal files, articles, reports, studies, legislative material,   pamphlets, newsletters, and news clippings pertaining to Boyden's career   as legal council for various western Native American Indian tribes.   Boyden received his J.D. degree from the University of Utah in 1967 and   has been affiliated with various groups dealing with Indian law and   tribal representation for most of his life.</p>

		<h4><a href="http://content.lib.utah.edu/cdm4/item_viewer.php?CISOROOT=/ww-EAD&amp;CISOPTR=0" target="_blank">C. Gregory Crampton Papers</a></h4>
		<p>The C. Gregory Crampton papers (1938-1979) contain research   materials on western history. Included are financial records from the   American West Publishing Company, maps, research on the Zuni and Ute   Indians, correspondence, clippings, bibliographies and catalogs,   pamphlets and publications. Also included are twenty oral history   transcripts of interviews conducted by students in History593 at the   University of Utah. C. Gregory Crampton (1911-1995) was professor   emeritus of history at the University of Utah and an author of works on   the history of Utah and the West.</p>

		<h4><a href="http://content.lib.utah.edu/u?/ww-EAD,7" target="_blank">Charles Eggert Papers</a></h4>
		<p>The Charles Eggert collection consists of slides documenting the   Eggert-Hatch Filming Expedition, the purpose of which was the make the   last films of the Green and Colorado Rivers before construction of the   Colorado River Storage Project was begun in 1956.  The collection also   includes photos taken during the creation of Canyonlands National Park   in Utah.  Eggert was a photographer and independent filmmaker from New   York.</p>

		<h4><a href="http://content.lib.utah.edu/u?/ww-EAD,3" target="_blank">Colorado Riverbed Case</a></h4>
		<p>The Colorado Riverbed Case records (1920-1931) consist of microfilm and   microfilm printouts from this court case which determined who legally   owned the riverbed of the Colorado River.</p>

		<h4><a href="http://content.lib.utah.edu/cdm4/item_viewer.php?CISOROOT=/ww-EAD&amp;CISOPTR=4" target="_blank">Dorothy Harvey Papers</a></h4>
		<p>The Dorothy Harvey papers (1902-2005) is a collection of materials   focusing on the Central Utah Project (CUP), a water resource development   program to use Utah's allotted share of the Colorado River. Includes   correspondence, Harvey's writing drafts and notes for an unpublished   book on the CUP, federal documents, project litigation materials,   subject files, news clippings, newsletters, programs, brochures, and   maps.</p>

		<h4><a href="http://content.lib.utah.edu/u?/ww-EAD,6" target="_blank">Flaming Gorge Dam Collection</a></h4>
		<p>The Flaming Gorge Dam collection consists of black and white prints of   photographs taken by the US Bureau of Reclamation during the   construction of Flaming Gorge Dam on the Green River.</p>

		<h4><a href="http://content.lib.utah.edu/u?/ww-EAD,5" target="_blank">Glen Canyon Archaeological Survey</a></h4>
		<p>The Glen Canyon Archaeological Survey collection contains photographs of   excavations, artifacts, and cliff dwellings taken during an   archaeological survey of Glen Canyon prior to its flooding. The survey   was headed by Jesse Jennings of the University of Utah Department of   Anthropology. Included are photographs of some of the members of the   survey party.</p>

		<h4><a href="http://content.lib.utah.edu/cdm4/item_viewer.php?CISOROOT=/ww-EAD&amp;CISOPTR=9" target="_blank">E. Richard Hart Papers</a></h4>
		<p>The E. Richard Hart papers (1664-2008) contain correspondence,   research files, manuscripts, news clippings, maps, publications, court   exhibits, and financial documents. Hart is an author, researcher, and   past director of the Institute of the American West at Sun Valley, Idaho   (1979-1984). He is the co-founder of the Institute of the North   American West (1984). He has also served as an expert witness in several   federal court cases involving land claims by the Zuni Indians.</p>

		<h4><a href="http://content.lib.utah.edu/u?/ww-EAD,18" target="_blank">Institute of the North American West</a></h4>
		<p>The Institute of the North American  West (INAW) records (1870-1993) consist of manuscripts, research materials and  notes, maps, interviews, court exhibits, correspondence, and publications. This  non-profit educational institution was established in 1984 by E. Richard Hart,  Matthew J. Cullen, and Barry Sadler for the purpose of providing historical background,  documentation, and opportunities for discussion of current thinking in regards  to environmental and cultural concerns, economic development, and problems  connected with these issues in the North American West, Canada to Mexico. </p>

		<h4><a href="http://content.lib.utah.edu/u?/ww-EAD,8" target="_blank">Floyd A. O’Neil</a></h4>
		<p>The Floyd A. O'Neil papers (1884-2006) contain documents from the   American West Center, Western Folklife Center, Indian Self Rule   Conference, and the Institute of the North American West. Included are   oral histories, research files, and both published and unpublished   documents related to O'Neil's position as a history professor at the   University of Utah, co-chair of the Western Folklife Center, and   director of the American West Center.</p>
		<p>&nbsp;</p>

		<h3>Washington State University</h3>

		<h4><a href="http://content.wsulibs.wsu.edu/cdm-koester/wwdl_ead.html">Clifford R. Koester Collection</a></h4>
		<p>The Clifford R. Koester collection housed at the Washington State   University Libraries Manuscript, Archives, and Special Collections   Department provides a unique, and sometimes overlooked, insight into the   community, construction, and evolution of the Columbia Basin Project   and specifically the Grand Coulee Dam.  As a long-time member of the   International Brotherhood of Electrical Workers (IBEW) and a resident of   the town of Coulee Dam (WA), Clifford Koester emphasized the workers’   experience in his photograph and project history.  In Koester’s <em>A History of the Columbia Basin Project</em>,   he focused on the contributions of laborers to this monumental project.   In the dedication, he observed that &quot;the ability and achievements of   the planners and engineers have often been extolled elsewhere. I wish to   speak now of the craftsmen and common workmen who toiled here, and gave   a part of their lives to further this great work…&quot; Koester’s collection   includes a reproduction of his unpublished three volume history focused   on the laborers and their project, as well as a number of newsletters   from several organizations active at the Dam site.</p>

		<h4><a href="http://content.wsulibs.wsu.edu/cdm-banks/wwdl_ead.html" target="_blank">Frank A Banks Papers</a></h4>
		<p>The papers consist of project histories of several Bureau of  		  Reclamation projects directed by Banks, ephemeral engineering publications  		  connected with the Grand Coulee Project, printed items of restricted  		  circulation such as engineering reports, and Banks' correspondence, notes and  		  papers re: private consultation projects, notably the Bhakra Dam in India. </p>
		<p>&nbsp;</p>

		<h3>Water Resources Center, UC Riverside</h3>
		<h4><a href="http://www.oac.cdlib.org/findaid/ark:/13030/tf9489p11x/" target="_blank">Frank Adams Papers, 1889-1962</a></h4>
		<p>The Adams Papers document the distinguished career and professional   activities of Frank Adams (1875-1967), including reports, reprints,   correspondence, clippings, and notes, concerning water, irrigation, and   land settlement projects in California, the Western States, and   Palestine; drafts of legislation pertaining to water, water rights, and   irrigation districts; minutes of meetings of various sections of the   Commonwealth Club of California; historical and statistical data on   California irrigation districts; and, extensive information on   University of California Irrigation Investigations in California. Frank   Adams was a celebrated professor of irrigation and international   consultant on agriculture, who was key to the development, distribution,   and use of water in the West.</p>
		<h4><a href="http://www.oac.cdlib.org/findaid/ark:/13030/tf4199n757/" target="_blank">John S. Eastwood Papers, 1884-1979 (bulk 1903-1924)</a></h4>
		<p>John Eastwood (1857-1924) developed the multiple arch dam and   designed numerous dams that were constructed in the western United   States. The collection includes correspondence, reports, designs,   specifications, and photographs, relating to dams, dam sites, and   hydroelectric power plants in Arizona, California, Idaho, Montana,   Nevada, New Mexico, Oregon, Utah, Wyoming, British Columbia, and Mexico.</p>
		<h4><a href="http://www.oac.cdlib.org/findaid/ark:/13030/tf32900395/" target="_blank">Walter L. Huber Photograph Collection, 1911-1953</a></h4>
		<p>The Walter L. Huber Photograph Collection contains 1,500   photographs of dams, reservoirs, and other water-related structures   taken by Walter L. Huber (1883-1960). His long and varied career as   engineer included hydroelectric and hydraulic assignments and projects,   such as: assistant to John Debo Galloway, Galloway &amp; Markwardt   Engineering Firm, 1905-1908; U.S. Forest Service, 1910-1913; the   California State Department of Public Works, many projects including San   Gabriel Dam No. 1 and Central Valley Project; construction engineer for   the California Debris Commission on arch dams; member of the board of   construction engineers of the U.S. War Department on flood control   projects on the Los Angeles, San Gabriel and Santa Ana Rivers including   Prado, Sepulveda, Brea, Fullerton, Santa Fe and Whittier Narrows Dams,   and in Central Valley, Isabella, Pine Flat and Iron Canyon Dams;   construction engineer for the City of San Francisco on Cherry Valley   Dam; regional water consultant, National Resources Planning Board; and   special consultant on earthquake resistant design of dams. (This   collection of images supplements the Walter L. Huber Papers collection,   held at the Water Resources Center Archives, University of California.)</p>
		<h4><a href="http://www.oac.cdlib.org/findaid/ark:/13030/tf958007kr/" target="_blank">Edward Hyatt Papers, 1924-1949</a></h4>
		<p>This collection includes articles, addresses by Edward Hyatt   (1888-1954), and clippings, pertaining to dams, water rights, salt water   intrusion, hydroelectric power, the California Water Plan, and other   aspects of water in California. Hyatt began his thirty-five year career   in the service of his native state as an engineer for the California   Highway Commission. In 1916 he transferred to the State Water   Commission, an agency created to administer state laws pertaining to   water rights. In 1921 the State Water Commission became part of the   Division of Water Rights of the State Department of Public Works; Mr.   Hyatt was appointed deputy chief and then chief of that division. In   1927 he was appointed State Engineer of California. Mr. Hyatt directed   surveys which led to the development of the State Water Plan, the basis   for the water conservation program in California, and of the Central   Valley Project.</p>
		<h4><a href="http://www.oac.cdlib.org/findaid/ark:/13030/tf7q2nb3b5/" target="_blank">Charles H. Lee Papers (bulk 1912-1955)</a></h4>
		<p>Charles Hamilton Lee (1883-1967) began his career as a hydrographer   for the U.S. Geological Survey but resigned in 1906 to become assistant   engineer for the city of Los Angeles. From 1906-1911, he was involved   in design and construction of the Los Angeles Aqueduct. During this   period his report on the groundwater basin of the Independence region of   the Owens Valley was published as U.S.G.S. <em>Water Supply Paper</em> 294. Lee was a consulting engineer on numerous projects and he   established the Pacific Hydrologic Laboratory, the first soils   engineering laboratory on the West Coast. He consulted on the fill   project which built Treasure Island, and from 1936-1939 he was chief of   Water Supply and Sanitation for the Golden Gate Exposition. The   collection contains reports, correspondence, documents, maps,   photographs, clippings, etc., pertaining to projects in hydraulics,   sanitation, irrigation, municipal water supply, surface water and   groundwater hydrology, and soil in California and other Western states,   particularly for the City of Los Angeles regarding water supply from the   Owens Valley. (This collection is supplemented by the Charles H. Lee   Photograph Collection, held at the Water Resources Center Archives,   University of California.)</p>
		<h4><a href="http://www.oac.cdlib.org/findaid/ark:/13030/tf3h4nb0ks/" target="_blank">Joseph Barlow Lippincott Papers, 1882-1942</a></h4>
		<p>The J.B. Lippincott collection contains correspondence, reports,   documents, clippings, and several descriptive photo albums (more than   5,000 photographs) pertaining to projects on dams, reservoirs,   aqueducts, and other water supply works, ground water and streamflow in   California, in particular for the Metropolitan Water District of   Southern California, and in Arizona and other Western States. Mr.   Lippincott (1882-1942) was a topographer for the USGS in the late 1890s   and became the assistant engineer for the Bear Valley Irrigation Company   on the construction of an early irrigation project on the Santa Ana   River. With the organization of the U.S. Reclamation Service in 1902,   Lippincott became supervising engineer of all Reclamation Service   activities in the Pacific Coast region from the Klamath River in Oregon   to the lower Colorado River in Arizona and California. In July 1906, Mr.   Lippincott left the Reclamation Service to become assistant chief   engineer of the Owens River Aqueduct.</p>
		<h4><a href="http://www.oac.cdlib.org/findaid/ark:/13030/tf5489n85p/" target="_blank">Thomas H. Means Papers (bulk 1905-1958)</a></h4>
		<p>Thomas Means' early career included nine years in the U.S.   Department of Agriculture, Bureau of Soils, during which time he was in   charge of soil surveys, principally in the western states. He served six   years in the Bureau of Reclamation in land examination and farm unit   subdivision and was in charge of a laboratory for the study of the   silt-carrying capacities of western streams. In 1910, Means went into   private practice in San Francisco, specializing in engineering connected   with agriculture, irrigation, drainage, reclamation and water supply.   He worked on the Central Valley Project and the Hetch Hetchy project,   and played a key role in court battles that led to water rights. The   collection includes correspondence and reports concerning the Colorado   River and flooding in the Imperial Valley, the Hetch Hetchy Project, Los   Angeles water supply, the Southern Sierra Power Company, the salinity   of San Francisco Bay and Sacramento-San Joaquin River Delta, flood   control and irrigation projects, groundwater, and land appraisal   throughout California and other western states.</p>
		<h4><a href="http://www.oac.cdlib.org/findaid/ark:/13030/kt5w10324n/" target="_blank">Milton N. Nathanson Papers, 1855-1995 (bulk 1965-1985)</a></h4>
		<p>The Milton N. Nathanson Papers consists of files Nathanson   (1910-2000) compiled during his work as an attorney specializing in   Colorado River water issues, including his employment at the Department   of Interior as Assistant Regional Solicitor and Field Solicitor and as   special consultant to the Department of Interior and the Coachella   Valley Water District, as well as notes and drafts written by Nathanson   while he was authoring the book, <em>Updating the Hoover Dam Documents,</em> and materials related to his involvement in the Colorado River Board of California. </p>
		<h4><a href="http://www.oac.cdlib.org/findaid/ark:/13030/tf3v19n78q/" target="_blank">James D. Schuyler Papers (bulk 1886-1912)</a></h4>
		<p>The James Dix Schuyler collection consists of unpublished reports,   correspondence, and other documents. The reports cover Schuyler's   (1848-1912) work as a consulting engineer in the Western U.S., Brazil,   Canada, Japan, Mexico, Panama, and Puerto Rico. Schuyler was the author   of <em>Reservoirs for Irrigation, Water Power, and Domestic Water Supply </em>(John Wiley &amp; Sons, 1901; 2nd edition, 1908), a work on dams, which for many years was a standard work on this subject.</p>
		<h4><a href="http://www.oac.cdlib.org/findaid/ark:/13030/tf32900395/" target="_blank">Walter L. Huber Photograph Collection</a></h4>

		<p>This   is a listing of photographs of dams, reservoirs, and other   water-related structures taken by Walter L. Huber. The list supplements our earlier Water   resources reports by Walter L. Huber: an annotated listing, Water   Resources Collections and Archives Series Report No. 12, May 1962. The materials are in the collection of the University of California's Water Resources Collections and Archives, Berkeley. </p>

